### ISSUE TITLE
Tort Phase Bins

### ISSUE THREAD

**Issue by mgm248** [pactools/pactools#10]
Hi,

Thanks for a great toolbox! 
I wanted to clarify over what phase range the MI is calculated over for the Tort method? It looks like the phase bins range from -pi to pi (phase_bins =  np.linspace(-np.pi, np.pi, n_bins)), but when plotting the Phase-Amplitude, the phase range for the x-axis is set to be phase_bins = 0.5 * (phase_bins[:-1] + phase_bins[1:]) / np.pi * 180 (-180 to 180, or -pi / 2 to pi / 2).

**Comment by TomDLT** [comment]
- Phase is returned by `np.angle` in [-pi, pi].
- Then it is digitized in the following bins: `phase_bins = np.linspace(-np.pi, np.pi, n_bins + 1)` using `np.digitize`.
- For plotting only, the digitized phase is showed in [-180, 180].

**Comment by mgm248** [comment]
Oh my mistake. Thank you for clarifying!
