### ISSUE TITLE
[General usage question-Feature Engineering]How to obtain unique PAC values for a group of patients in the 1020 electrode system?

### ISSUE THREAD

**Issue by akatav** [pactools/pactools#19]
Hi
Noobie question here - I have a large number of patients whose EEG is recorded using 19 electrodes (single trial, eyes closed, resting). I would like to know, if there is a way to obtain the PAC values for a patient (say, by each electrode) ? I am trying to incorporate CFC PAC as a possible feature in my EEG dataset (after feature engineering/building from raw eeg data using various non linear and linear techniques). 
The comod_ attribute in the Comodulogram() object provides a (low_freq_range, high_freq_range) 2d array for each electrode for each patient, as per my present code/understanding. I'd like to know a way to consolidate the comodulogram values so as to represent that with a single feature (per electrode) ? Can you please provide an example of how this can be done ?

**Comment by TomDLT** [comment]
It depends what information you want to keep.
You might want to keep the couple of frequencies of the maximum, or the PAC value at maximum.
In any case, you will lose a lot of information contained in the 2d distribution.

This question is quite interesting but it is more a research question than a package use question.

**Comment by akatav** [comment]
@TomDLT i am doing get_maximum_pac_value() to get a single value as required above between two channels for some (low,high) frequency range. is that correct ?

**Comment by TomDLT** [comment]
It is definitely one way of getting a single value out of a comodulogram.
Summarizing the comodulogram with a single value will ignore a lot of information, it's up to you to decide what information you want to keep in your analysis.
