### ISSUE TITLE
[ENH] Use simulated data instead of MNE sample data for I/O demo

### ISSUE THREAD

**Issue by alexrockhill** [pactools/pactools#24]
Since I already wrote most of how to do that here: https://github.com/pactools/pactools/pull/22, I could change a few lines around so that you make an MNE object with PAC, save it to a temp directory, load it in and compute PAC. IMO that would make a better example.

This is in reference to this demo: https://pactools.github.io/auto_examples/plot_mne_epoch_masking.html.

**Comment by TomDLT** [comment]
Yes, that would be a much better example !
