### ISSUE TITLE
(Question) Interpreting phase 

### ISSUE THREAD

**Issue by mgm248** [pactools/pactools#29]
Hello,

Could you clarify how to interpret the driver phase? In the driver waveform, I believe 0 degrees corresponds to the peak, 180d is the trough, -90d is the rising zero crossing, and 90d is the falling zero crossing --  is this correct? 

If so, why is this the case, instead of 90d corresponding to the peak, and -90d corresponding to the trough, as phase is normally interpreted for a sine wave? I first thought this was due to the Hilbert transform, but I now understand the default bandpass filter does not use the Hilbert transform.

Thank you!

**Comment by TomDLT** [comment]
> Could you clarify how to interpret the driver phase? In the driver waveform, I believe 0 degrees corresponds to the peak, 180d is the trough, -90d is the rising zero crossing, and 90d is the falling zero crossing -- is this correct?

Correct. You can see an example at https://pactools.github.io/auto_examples/plot_phase_delay.html#sphx-glr-auto-examples-plot-phase-delay-py

> If so, why is this the case, instead of 90d corresponding to the peak, and -90d corresponding to the trough, as phase is normally interpreted for a sine wave?

It corresponds to a cosine instead of a sine, and this choice is arbitrary.

**Comment by mgm248** [comment]
Perfect, thank you for clarifying!
