### ISSUE TITLE
binary incompatibility warning

### ISSUE THREAD

**Issue by mehdikuchi** [pactools/pactools#35]
Dear Developers,

I have installed the pactools using pip command. My python version is 3.8.5 under win 10, and conda version 4.10.3.
After importing the library I got the following warnings:

![image](https://user-images.githubusercontent.com/43707267/137694830-6a2db92f-290c-4433-b805-e5586e3bd9b0.png)

**Comment by TomDLT** [comment]
Hi, these warnings seem unrelated with pactools.
The first one is about numpy, and you might want to try reinstalling numpy.
The second is about ipython, and I would just ignore it.

**Comment by mehdikuchi** [comment]
Thanks for the reply,
I had tried the reinstallation of numpy with pip but now I have also done it using conda command. Now after importing the pactools I still got the warning but not for the numpy (second warning is gone). As you mentioned I can just ignore it. 
Thanks a lot, I wanted to be sure.
